ELEMENT_1 = "Plutonium"
ELEMENT_1_MICROCHIP_STRING = "PM"
ELEMENT_1_GENERATOR_STRING = "PG"

ELEMENT_2 = "Strontium"
ELEMENT_2_MICROCHIP_STRING = "SM"
ELEMENT_2_GENERATOR_STRING = "SG"

INVALID_FLOOR_ITEM_TYPE = "X"
